# Generated by Django 4.2 on 2023-07-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_nickname', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_time', models.TimeField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.CharField(blank=True, max_length=100, null=True)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('client_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('client_phone_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('durations', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('order_status', models.CharField(blank=True, choices=[('Awaiting Payment', 'Awaiting Payment'), ('Confirming Payment', 'Confirming Payment'), ('Payment Received', 'Payment Received'), ('Order Completed', 'Order Completed'), ('Order Cancelled', 'Order Cancelled')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_nickname', models.CharField(blank=True, max_length=1000)),
                ('state', models.CharField(blank=True, max_length=1000)),
                ('address', models.CharField(blank=True, max_length=1000)),
                ('lat', models.CharField(blank=True, max_length=1000)),
                ('lng', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_value', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_tag', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('social_username', models.CharField(blank=True, max_length=200, null=True)),
                ('social_network', models.CharField(blank=True, max_length=200, null=True)),
                ('testimony', models.CharField(blank=True, max_length=200, null=True)),
                ('ratings', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
